<ADSWorkspace Revision="3" Version="100">
    <Workspace Name="">
        <LibraryDefs Name="lib.defs" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Preferences Name="layout.prf" />
        <Preferences Name="schematic.prf" />
        <Library Name="ads_standard_layers" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_builtin" />
        <Library Name="ads_standard_layers_ic" />
        <Library Name="ads_schematic_layers_ic" />
        <Library Name="ads_schematic_ports_ic" />
        <Library Name="ads_rflib" />
        <Library Name="ads_sources" />
        <Library Name="ads_simulation" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_datacmps" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_pelib" />
        <Library Name="ads_serdes_ref_channel" />
        <Library Name="CHW3_Q1_lib" />
        <Log Name="search_history.log" />
        <ConfigFile Name="dds.cfg" />
        <Data_Display Name="1db compression point &amp;&amp; IIP3.dds" />
        <Log Name="netlist.log" />
        <Preferences Name="CHW3_Q1_lib_lay.prf" />
        <Dataset Name="_1db_compression_point____IIP3.ds" />
        <Data_Files Name="dc_annotation\%C%H%W3_%Q1_lib_1db#20compression#20point#20#26#26#20%I%I%P3_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%C%H%W3_%Q1_lib_1db#20compression#20point#20#26#26#20%I%I%P3_schematic\annotation_map.xml" />
        <Data_Files Name="_1db_compression_point____IIP3.ds" />
        <Data_Files Name="_1db_compression_point____IIP3_data\logFile.txt" />
        <Library Name="TSMC18RF" />
        <Cell Name="CHW3_Q1_lib:1db compression point &amp;&amp; IIP3" />
        <Cell Name="CHW3_Q1_lib:1db compression point &amp;&amp; IIP3_v1" />
        <Dataset Name="_1db_compression_point____IIP3_v1.ds" />
        <Data_Files Name="dc_annotation\%C%H%W3_%Q1_lib_1db#20compression#20point#20#26#26#20%I%I%P3_v1_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%C%H%W3_%Q1_lib_1db#20compression#20point#20#26#26#20%I%I%P3_v1_schematic\annotation_map.xml" />
        <Data_Files Name="_1db_compression_point____IIP3_v1.ds" />
        <Data_Files Name="_1db_compression_point____IIP3_v1_data\logFile.txt" />
        <Data_Display Name="1db compression point &amp;&amp; IIP3_v1.dds" />
    </Workspace>
</ADSWorkspace>
